name: ci

on:
  push:
    branches:
      - master
#  schedule:
#    - cron: "3 11,17 * * *"

jobs:
  autogreen:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Test auto
        run: |
          git config --local user.email "brinarickeych@outlook.com"
          git config --local user.name "brina5"
          git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git pull --rebase
          git commit --allow-empty -m "test auto"
          git push
